In [14]:
import pandas as pd
from os import listdir
from os.path import isfile, join

In [15]:
mypath = './data/'

In [16]:
onlyfiles = [mypath + f for f in listdir(mypath) if isfile(join(mypath, f))]

In [17]:
onlyfiles

['./data/otomoto_0-25000.pickle',
 './data/otomoto_100001-125000.pickle',
 './data/otomoto_125001-150000.pickle',
 './data/otomoto_25001-50000.pickle',
 './data/otomoto_50001-75000.pickle',
 './data/otomoto_75001-100000.pickle',
 './data/otomoto_data.pickle',
 './data/otomoto_data_test_vshort.pickle']

In [18]:
onlyfiles = onlyfiles[:-2]

In [20]:
onlyfiles

['./data/otomoto_0-25000.pickle',
 './data/otomoto_100001-125000.pickle',
 './data/otomoto_125001-150000.pickle',
 './data/otomoto_25001-50000.pickle',
 './data/otomoto_50001-75000.pickle',
 './data/otomoto_75001-100000.pickle']

In [21]:
data = pd.read_pickle(onlyfiles[0])
print(onlyfiles[0])
for file in onlyfiles[1:]:
    print(file)
    data = pd.concat([data, pd.read_pickle(file)])

./data/otomoto_0-25000.pickle
./data/otomoto_100001-125000.pickle
./data/otomoto_125001-150000.pickle
./data/otomoto_25001-50000.pickle
./data/otomoto_50001-75000.pickle
./data/otomoto_75001-100000.pickle

In [22]:
data.shape[0]

130919

In [23]:
data = data.drop_duplicates()
data.shape[0]

130804

In [24]:
data.head()

,price,Oferta od,Kategoria,Marka pojazdu,Model pojazdu,Rok produkcji,Przebieg,Pojemność skokowa,Rodzaj paliwa,Moc,...,Okres gwarancji producenta,Kierownica po prawej (Anglik),Generacja,VIN,Zarejestrowany jako zabytek,Homologacja ciężarowa,Średnie zużycie,Pojemność baterii,Autonomia,Czas ładowania
0,39 900 PLN,Firmy,Osobowe,Abarth,Inny,2009,158 000 km,1 368 cm3,Benzyna,215 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,72 900 PLN,Firmy,Osobowe,Abarth,500,2019,66 500 km,1 368 cm3,Benzyna,145 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39 900 PLN,Osoby prywatnej,Osobowe,Abarth,500,2012,193 631 km,1 400 cm3,Benzyna,135 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,43 900 PLN,Osoby prywatnej,Osobowe,Abarth,500,2015,139 000 km,1 368 cm3,Benzyna,160 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,36 500 PLN,Osoby prywatnej,Osobowe,Abarth,500,2013,103 000 km,1 368 cm3,Benzyna,160 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
data

,price,Oferta od,Kategoria,Marka pojazdu,Model pojazdu,Rok produkcji,Przebieg,Pojemność skokowa,Rodzaj paliwa,Moc,...,Okres gwarancji producenta,Kierownica po prawej (Anglik),Generacja,VIN,Zarejestrowany jako zabytek,Homologacja ciężarowa,Średnie zużycie,Pojemność baterii,Autonomia,Czas ładowania
0,39 900 PLN,Firmy,Osobowe,Abarth,Inny,2009,158 000 km,1 368 cm3,Benzyna,215 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,72 900 PLN,Firmy,Osobowe,Abarth,500,2019,66 500 km,1 368 cm3,Benzyna,145 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39 900 PLN,Osoby prywatnej,Osobowe,Abarth,500,2012,193 631 km,1 400 cm3,Benzyna,135 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,43 900 PLN,Osoby prywatnej,Osobowe,Abarth,500,2015,139 000 km,1 368 cm3,Benzyna,160 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,36 500 PLN,Osoby prywatnej,Osobowe,Abarth,500,2013,103 000 km,1 368 cm3,Benzyna,160 KM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22228,124 900 PLN,Firmy,Osobowe,Peugeot,3008,2021,14 000 km,1 499 cm3,Diesel,130 KM,...,10/05/2023,NaN,II (2016-),NaN,NaN,NaN,NaN,NaN,NaN,NaN
22229,129 900 PLN,Firmy,Osobowe,Peugeot,3008,2021,1 km,1 199 cm3,Benzyna,130 KM,...,NaN,NaN,II (2016-),NaN,NaN,NaN,NaN,NaN,NaN,NaN
22230,138 300 PLN,Firmy,Osobowe,Peugeot,3008,2021,1 km,1 199 cm3,Benzyna,130 KM,...,NaN,NaN,II (2016-),NaN,NaN,NaN,NaN,NaN,NaN,NaN
22231,179 000 PLN,Firmy,Osobowe,Peugeot,3008,2022,2 km,1 199 cm3,Benzyna,130 KM,...,NaN,NaN,II (2016-),NaN,NaN,NaN,NaN,NaN,NaN,NaN
22232,144 900 PLN,Firmy,Osobowe,Peugeot,3008,2022,5 km,1 199 cm3,Benzyna,130 KM,...,NaN,NaN,II (2016-),NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
data.to_pickle('data/otomoto_data.pickle')